apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: work-queue
    component: queue
    chapter: jobs
  name: queue
spec:
  selector:
    matchLabels:
      app: work-queue
      component: queue
      chapter: jobs
  replicas: 1
  template:
    metadata:
      labels:
        app: work-queue
        component: queue
        chapter: jobs
    spec:
      containers:
      - name: queue
        image: " europe-west1-docker.pkg.dev/k8s-formation/k8s-lab/kuard:blue"
        imagePullPolicy: Always
