# Simplified template
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newapp
  namespace: argocd
spec:
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/kiowy-org/k8s-lab.git  # Git Reposition URL
    targetRevision: HEAD  # Keep Helm
    path:  5_argo_cd/applications/guestbook/overlays/staging  # Path to Kustomization of your folder

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated:
      prune: true 
