apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image:  europe-west1-docker.pkg.dev/k8s-formation/k8s-lab/kuard:blue
      name: kuard
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP