apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: "kuard-data"
      emptyDir: {}      
  containers:
    - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/kuard:blue
      name: kuard
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
