apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard
    env: prod
  name: kuard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kuard
      env: prod
  strategy: {}
  template:
    metadata:
      labels:
        app: kuard
        env: prod
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard-amd64
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
